# Generated by Django 3.1.5 on 2021-01-31 04:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('backend', '0004_auto_20210131_0038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Mission',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='goals',
            new_name='mission',
        ),
    ]
