# Generated by Django 3.1.5 on 2021-01-31 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210131_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='goal',
            new_name='mission',
        ),
    ]
