# Generated by Django 3.1.5 on 2021-01-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210131_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='mission',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
